/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ScoringInterface extends Interface {
  getFunction(
    nameOrSignature: "addScore" | "owner" | "scores"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ScoreRecorded"): EventFragment;

  encodeFunctionData(
    functionFragment: "addScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "scores", values: [AddressLike]): string;

  decodeFunctionResult(functionFragment: "addScore", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "scores", data: BytesLike): Result;
}

export namespace ScoreRecordedEvent {
  export type InputTuple = [user: AddressLike, score: BigNumberish];
  export type OutputTuple = [user: string, score: bigint];
  export interface OutputObject {
    user: string;
    score: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Scoring extends BaseContract {
  connect(runner?: ContractRunner | null): Scoring;
  waitForDeployment(): Promise<this>;

  interface: ScoringInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addScore: TypedContractMethod<[_score: BigNumberish], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  scores: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addScore"
  ): TypedContractMethod<[_score: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "scores"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "ScoreRecorded"
  ): TypedContractEvent<
    ScoreRecordedEvent.InputTuple,
    ScoreRecordedEvent.OutputTuple,
    ScoreRecordedEvent.OutputObject
  >;

  filters: {
    "ScoreRecorded(address,uint256)": TypedContractEvent<
      ScoreRecordedEvent.InputTuple,
      ScoreRecordedEvent.OutputTuple,
      ScoreRecordedEvent.OutputObject
    >;
    ScoreRecorded: TypedContractEvent<
      ScoreRecordedEvent.InputTuple,
      ScoreRecordedEvent.OutputTuple,
      ScoreRecordedEvent.OutputObject
    >;
  };
}
